services:
  - type: web
    name: rai-compliance-backend
    env: python
    plan: starter
    pythonVersion: "3.11.9"
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AZURE_OPENAI_API_KEY
        sync: false
      - key: AZURE_OPENAI_ENDPOINT
        sync: false
      - key: AZURE_OPENAI_DEPLOYMENT_NAME
        value: model-router
      - key: AZURE_OPENAI_API_VERSION
        value: 2024-12-01-preview
      - key: AZURE_OPENAI_EMBEDDING_DEPLOYMENT
        value: text-embedding-ada-002
      - key: AZURE_OPENAI_EMBEDDING_API_VERSION
        value: 2023-05-15
    healthCheckPath: /api/v1/health